TOPLEVEL_LANG = verilog
TOPLEVEL      = axi_crossbar
MODULE        = test_crossbar

SIM           = verilator
EXTRA_ARGS   += --trace --trace-structs -Wno-fatal

VERILOG_SOURCES = \
    $(PWD)/../../rtl/top/axi_addr_decoder.sv \
    $(PWD)/../../rtl/top/axi_arbiter.sv \
    $(PWD)/../../rtl/top/axi_crossbar.sv

include $(shell cocotb-config --makefiles)/Makefile.sim
