/* Auto-generated by gen_dram_init_multitile.py — DO NOT EDIT */
#ifndef INFERENCE_CONFIG_MULTITILE_H
#define INFERENCE_CONFIG_MULTITILE_H

#include <stdint.h>

/* ---- DRAM base addresses ---- */
#define DRAM_BASE_UC        0x60000000u
#define DRAM_BASE_CACHED    0x40000000u

/* ---- Multi-tile geometry ---- */
#define N_PARALLEL          4u
#define ROOT_TILE           0u

/* ---- FC1 dimensions ---- */
#define FC1_M_ORIG          140u
#define FC1_K_ORIG          9216u
#define FC1_M_PADDED        144u
#define FC1_K_PADDED        9216u
#define FC1_NUM_M_TILES     9u
#define FC1_NUM_K_TILES     576u

/* ---- FC2 dimensions ---- */
#define FC2_M_ORIG          10u
#define FC2_K_ORIG          140u
#define FC2_M_PADDED        16u
#define FC2_K_PADDED        144u
#define FC2_NUM_M_TILES     1u
#define FC2_NUM_K_TILES     9u

/* ---- Scratchpad layout (words) ---- */
#define SYSTOLIC_DIM        16u
#define BLOCK_WORDS         64u  /* 64 words per 16×16 INT8 block */
#define SP_RESULT_WORDS     256u   /* 16×16 INT32 = 256 words */
#define SP_WGT_BASE         0u
#define SP_ACT_BASE         64u
#define SP_OUT_BASE         128u

/* ---- Per-tile FC1 BSR offsets (word offsets in DRAM) ---- */
#define FC1_MT_INDPTR_OFFSET_W0    0x00001000u
#define FC1_MT_INDPTR_OFFSET_W1    0x00002cbbu
#define FC1_MT_INDPTR_OFFSET_W2    0x00004935u
#define FC1_MT_INDPTR_OFFSET_W3    0x0000656eu

#define FC1_MT_INDICES_OFFSET_W0   0x0000100au
#define FC1_MT_INDICES_OFFSET_W1   0x00002cc5u
#define FC1_MT_INDICES_OFFSET_W2   0x0000493fu
#define FC1_MT_INDICES_OFFSET_W3   0x00006578u

#define FC1_MT_DATA_OFFSET_W0      0x0000107bu
#define FC1_MT_DATA_OFFSET_W1      0x00002d35u
#define FC1_MT_DATA_OFFSET_W2      0x000049aeu
#define FC1_MT_DATA_OFFSET_W3      0x000065e4u

/* ---- Shared FC1 activation ---- */
#define FC1_ACT_OFFSET          0x000080e4u

/* ---- Per-tile FC1 partial scratch ---- */
/* Layout: [0..15] = INT32 accumulator, [16..271] = per-block output */
#define FC1_PARTIAL_OFFSET_W0      0x000110e4u
#define FC1_PARTIAL_OFFSET_W1      0x000111f4u
#define FC1_PARTIAL_OFFSET_W2      0x00011304u
#define FC1_PARTIAL_OFFSET_W3      0x00011414u

/* ---- FC1 accumulated output ---- */
#define FC1_OUT_OFFSET          0x00011524u

/* ---- FC2 regions (full pipeline with FC1 prefix) ---- */
#define FC2_WEIGHT_OFFSET       0x00000000u
#define FC2_ACT_OFFSET          0x000115b4u
#define FC2_OUTPUT_OFFSET       0x000117f4u

/* ---- Convenience arrays (initialise in C) ---- */
/* Use  MT_INDPTR_OFFSETS[w]  etc. to index by tile id. */
#define MT_INDPTR_OFFSETS  { \
    0x00001000u,\
    0x00002cbbu,\
    0x00004935u,\
    0x0000656eu \
}

#define MT_INDICES_OFFSETS  { \
    0x0000100au,\
    0x00002cc5u,\
    0x0000493fu,\
    0x00006578u \
}

#define MT_DATA_OFFSETS  { \
    0x0000107bu,\
    0x00002d35u,\
    0x000049aeu,\
    0x000065e4u \
}

#define MT_PARTIAL_OFFSETS  { \
    0x000110e4u,\
    0x000111f4u,\
    0x00011304u,\
    0x00011414u \
}

#define TRUE_LABEL          7u
#define GOLDEN_PREDICTION   7u

#endif /* INFERENCE_CONFIG_MULTITILE_H */
