/* Auto-generated by gen_dram_init.py --full — DO NOT EDIT */
#ifndef INFERENCE_CONFIG_FULL_H
#define INFERENCE_CONFIG_FULL_H

#define DRAM_BASE_UC        0x60000000u
#define DRAM_BASE_CACHED    0x40000000u

/* FC1 BSR layer: 140x9216 — 444 nonzero 16x16 blocks */
#define FC1_BSR_INDPTR_OFFSET  0x00001000u  /* 10 words */
#define FC1_BSR_INDICES_OFFSET 0x0000100au  /* 444 words */
#define FC1_BSR_DATA_OFFSET    0x000011c6u  /* NNZ*64 words */
#define FC1_BSR_NNZ            444u
#define FC1_M_ORIG          140u
#define FC1_K_ORIG          9216u
#define FC1_M_PADDED        144u
#define FC1_K_PADDED        9216u
#define FC1_NUM_M_TILES     9u
#define FC1_NUM_K_TILES     576u
#define FC1_ACT_OFFSET      0x000080c6u
#define FC1_PARTIAL_OFFSET  0x000110c6u
#define FC1_OUT_OFFSET      0x000111c6u

/* FC2 layer: 10x140 */
#define FC2_WEIGHT_OFFSET   0x00000000u
#define FC2_M_ORIG          10u
#define FC2_K_ORIG          140u
#define FC2_M_PADDED        16u
#define FC2_K_PADDED        144u
#define FC2_NUM_M_TILES     1u
#define FC2_NUM_K_TILES     9u
#define FC2_ACT_OFFSET      0x00011256u
#define FC2_OUTPUT_OFFSET   0x00011496u

#define SYSTOLIC_DIM        16u
#define BLOCK_WORDS         (16u * 16u / 4u)

#define TRUE_LABEL          7u
#define GOLDEN_PREDICTION   7u

#endif /* INFERENCE_CONFIG_FULL_H */
