/* Auto-generated by gen_dram_init.py — DO NOT EDIT */
#ifndef INFERENCE_CONFIG_H
#define INFERENCE_CONFIG_H

#define DRAM_BASE_UC        0x60000000u
#define DRAM_BASE_CACHED    0x40000000u

/* FC2 layer: 10x140 */
#define FC2_WEIGHT_OFFSET   0x00000000u  /* word offset */
#define FC2_M_ORIG          10u
#define FC2_K_ORIG          140u
#define FC2_M_PADDED        16u
#define FC2_K_PADDED        144u
#define FC2_NUM_M_TILES     1u
#define FC2_NUM_K_TILES     9u

#define ACT_OFFSET          0x00000240u  /* word offset */
#define OUTPUT_OFFSET       0x00000480u  /* word offset */

#define SYSTOLIC_DIM        16u
#define BLOCK_WORDS         (16u * 16u / 4u)  /* 64 words per 16x16 INT8 block */
#define ACT_BLOCK_WORDS     BLOCK_WORDS  /* 64 words per 16x16 activation block */

#define TRUE_LABEL          7u
#define GOLDEN_PREDICTION   7u

#endif /* INFERENCE_CONFIG_H */
