// ============================================================================
// main_inference_full.c — Full MNIST FC1+FC2 on-chip firmware (BSR-sparse FC1)
// ============================================================================
// Runs FC1 (140×9216, 91% sparse) + FC2 (10×140) entirely on the tile array.
//
//   Step 1: BSR GEMV for FC1 — only nonzero 16×16 blocks are sent to hardware
//     For each FC1 M-tile (0..FC1_NUM_M_TILES-1):
//       read BSR row slice: indptr[m]..indptr[m+1] → list of K-block indices
//       For each nonzero K-tile j in that row:
//         - DMA weight block (BSR data[j]) + act block[k] into scratchpad
//         - OP_COMPUTE → partial product
//         - CPU accumulates into running m_logits[16]
//       CPU writes m_logits to FC1_OUT, applies ReLU
//
//   Step 2: CPU quantises FC1 output → INT8 GEMV blocks for FC2
//   Step 3: FC2 dense GEMV on tile 0 (10×144, 9 K-tiles)
//   Step 4: Argmax, UART print
//
// BSR DRAM layout (generated by gen_dram_init.py --full):
//   FC1_BSR_INDPTR_OFFSET  — uint32[M_tiles+1]  row-block pointers
//   FC1_BSR_INDICES_OFFSET — uint32[NNZ]        K-block col indices
//   FC1_BSR_DATA_OFFSET    — int8[NNZ×256]      16×16 weight blocks (packed 4/word)
//   FC1_ACT_OFFSET         — int8 GEMV blocks   input activation (K-major)
// ============================================================================

#include <stdint.h>
#include <stdbool.h>
#include "hal.h"
#include "hal_accel.h"
#include "inference_config_full.h"

// ────────────────────────────────────────────────────────────────────────────
// UART helpers (identical to main_inference.c)
// ────────────────────────────────────────────────────────────────────────────
static void uart_putc(char c)
{
    while (REG32(UART_STATUS) & UART_STATUS_TX_FULL)
        ;
    REG8(UART_TX_DATA) = (uint8_t)c;
}

static void uart_puts(const char *s)
{
    while (*s)
        uart_putc(*s++);
}

static void uart_put_hex(uint32_t val)
{
    static const char hex[] = "0123456789abcdef";
    for (int i = 28; i >= 0; i -= 4)
        uart_putc(hex[(val >> i) & 0xF]);
}

static void uart_put_dec(int32_t val)
{
    if (val < 0) {
        uart_putc('-');
        uint32_t uval = (uint32_t)(-(val + 1)) + 1u;
        uart_put_dec((int32_t)uval);
        return;
    }
    char buf[12];
    int i = 0;
    if (val == 0) { uart_putc('0'); return; }
    uint32_t uv = (uint32_t)val;
    while (uv > 0) {
        uint32_t q = 0, rem = uv;
        while (rem >= 10u) { rem -= 10u; q++; }
        buf[i++] = '0' + (char)rem;
        uv = q;
    }
    for (int j = i - 1; j >= 0; j--)
        uart_putc(buf[j]);
}

static uint32_t timer_read(void)
{
    return REG32(MTIME_LO);
}

// ────────────────────────────────────────────────────────────────────────────
// Absolute value (no libc)
// ────────────────────────────────────────────────────────────────────────────
static inline int32_t abs32(int32_t x)
{
    return (x < 0) ? -x : x;
}

// ────────────────────────────────────────────────────────────────────────────
// Scratchpad layout (words)
// ────────────────────────────────────────────────────────────────────────────
#define SP_WGT_BASE       0u
#define SP_ACT_BASE       64u
#define SP_OUT_BASE       128u
#define SP_RESULT_WORDS   256u     // 16×16 INT32

// Tile 0 used for all ops
#define TILE_ID           0u

// ────────────────────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────────────────────
int main(void)
{
    // Peripherals
    REG32(UART_CTRL) = UART_CTRL_TX_EN | UART_CTRL_RX_EN;
    REG32(GPIO_DIR)  = 0xFFu;
    REG32(GPIO_OUT)  = 0x01u;   // LED0 = booted

    uart_puts("MNIST full-chain firmware (fc1+fc2)\r\n");
    uart_puts("FC1: ");
    uart_put_dec(FC1_M_ORIG);
    uart_putc('x');
    uart_put_dec(FC1_K_ORIG);
    uart_puts(" → ");
    uart_put_dec(FC1_NUM_M_TILES);
    uart_puts("M × ");
    uart_put_dec(FC1_NUM_K_TILES);
    uart_puts("K tiles\r\n");
    uart_puts("FC2: ");
    uart_put_dec(FC2_M_ORIG);
    uart_putc('x');
    uart_put_dec(FC2_K_ORIG);
    uart_puts("\r\n");

    REG32(GPIO_OUT) = 0x02u;    // LED1 = inference running

    uint32_t t_start = timer_read();

    // ════════════════════════════════════════════════════════════════════════
    // STEP 1 — FC1 BSR GEMV: W_fc1[FC1_M_PADDED × FC1_K_PADDED] × x[FC1_K]
    // ════════════════════════════════════════════════════════════════════════
    // BSR metadata in DRAM (read as 32-bit words via uncached port):
    //   indptr[FC1_NUM_M_TILES+1]  at FC1_BSR_INDPTR_OFFSET
    //   indices[FC1_BSR_NNZ]       at FC1_BSR_INDICES_OFFSET
    //   data[FC1_BSR_NNZ × 64wds]  at FC1_BSR_DATA_OFFSET   (sequential)
    //
    // For each M-tile m, we iterate only over its nonzero K-tile blocks,
    // skipping ~91% of blocks entirely → ~10× fewer systolic ops vs dense.

    for (uint32_t m = 0; m < FC1_NUM_M_TILES; m++) {

        // Zero running partial sum (stored in DRAM uncached scratch)
        uint32_t partial_addr = DRAM_BASE_UC + FC1_PARTIAL_OFFSET * 4u;
        for (uint32_t i = 0; i < SYSTOLIC_DIM; i++)
            REG32(partial_addr + i * 4u) = 0u;

        // Read BSR row pointers for this M-tile
        uint32_t row_start = REG32(DRAM_BASE_UC + FC1_BSR_INDPTR_OFFSET * 4u
                                   + m * 4u);
        uint32_t row_end   = REG32(DRAM_BASE_UC + FC1_BSR_INDPTR_OFFSET * 4u
                                   + (m + 1u) * 4u);

        for (uint32_t j = row_start; j < row_end; j++) {

            // K-block column index for this nonzero block
            uint32_t k = REG32(DRAM_BASE_UC + FC1_BSR_INDICES_OFFSET * 4u
                               + j * 4u);

            // BSR data[j]: the j-th 16×16 INT8 block (64 words, sequential)
            uint32_t wgt_word_off = FC1_BSR_DATA_OFFSET + j * BLOCK_WORDS;
            uint32_t wgt_addr     = DRAM_BASE_CACHED + wgt_word_off * 4u;

            // Activation block at K-tile k (K-major, same as dense layout)
            uint32_t act_word_off = FC1_ACT_OFFSET + k * BLOCK_WORDS;
            uint32_t act_addr     = DRAM_BASE_CACHED + act_word_off * 4u;

            // Scratch for this tile's partial output
            uint32_t out_word_off = FC1_PARTIAL_OFFSET + SYSTOLIC_DIM; // after partial
            uint32_t out_addr     = DRAM_BASE_CACHED + out_word_off * 4u;

            // 1. Load weight block
            accel_load(TILE_ID, wgt_addr, BLOCK_WORDS, SP_WGT_BASE);
            accel_wait_idle(TILE_ID);

            // 2. Load activation block
            accel_load(TILE_ID, act_addr, BLOCK_WORDS, SP_ACT_BASE);
            accel_wait_idle(TILE_ID);

            // 3. Compute partial product (16×16 × 16×16 → 16×16 INT32)
            accel_compute_at(TILE_ID, SP_ACT_BASE, SP_WGT_BASE, SP_OUT_BASE);
            accel_wait_idle(TILE_ID);

            // 4. Store output
            accel_store(TILE_ID, out_addr, SP_RESULT_WORDS, SP_OUT_BASE);
            accel_wait_idle(TILE_ID);

            // 5. CPU fold: sum 16 rows into partial (column-major accumulate)
            uint32_t scratch_uc = DRAM_BASE_UC + out_word_off * 4u;
            for (uint32_t row = 0; row < SYSTOLIC_DIM; row++) {
                for (uint32_t col = 0; col < SYSTOLIC_DIM; col++) {
                    uint32_t word_off = row * SYSTOLIC_DIM + col;
                    int32_t  val      = (int32_t)REG32(scratch_uc + word_off * 4u);
                    uint32_t acc_off  = partial_addr + col * 4u;
                    REG32(acc_off)    = (uint32_t)((int32_t)REG32(acc_off) + val);
                }
            }
        } // end nonzero K-block loop

        // Write this M-tile's output into FC1_OUT region and apply ReLU
        uint32_t fc1_out_base = DRAM_BASE_UC + FC1_OUT_OFFSET * 4u
                              + m * SYSTOLIC_DIM * 4u;
        for (uint32_t col = 0; col < SYSTOLIC_DIM; col++) {
            int32_t val = (int32_t)REG32(partial_addr + col * 4u);
            if (val < 0) val = 0;   // ReLU
            REG32(fc1_out_base + col * 4u) = (uint32_t)val;
        }
    } // end M-tile loop

    // ════════════════════════════════════════════════════════════════════════
    // STEP 2 — Quantise FC1 output to INT8 (power-of-2 shift)
    // ════════════════════════════════════════════════════════════════════════
    uint32_t fc1_out_base_uc = DRAM_BASE_UC + FC1_OUT_OFFSET * 4u;

    // Find max value (all inputs are >= 0 after ReLU)
    int32_t max_val = 1;   // avoid divide-by-zero
    for (uint32_t i = 0; i < FC1_M_ORIG; i++) {
        int32_t v = (int32_t)REG32(fc1_out_base_uc + i * 4u);
        if (v > max_val) max_val = v;
    }

    // Compute right-shift so that max_val >> shift <= 127
    uint32_t shift = 0;
    while ((max_val >> shift) > 127) shift++;

    // Quantise and write INT8 to FC2 activation region as GEMV blocks
    // Block format: row 0 = x[k*16..(k+1)*16], other rows = 0
    for (uint32_t k = 0; k < FC2_NUM_K_TILES; k++) {
        uint32_t blk_base = DRAM_BASE_UC
                          + (FC2_ACT_OFFSET + k * BLOCK_WORDS) * 4u;
        // Zero the 16×16 block
        for (uint32_t w = 0; w < (SYSTOLIC_DIM * SYSTOLIC_DIM / 4u); w++)
            REG32(blk_base + w * 4u) = 0u;
        // Pack row 0: 16 INT8 values into 4 words (little-endian)
        for (uint32_t col = 0; col < SYSTOLIC_DIM; col++) {
            uint32_t idx = k * SYSTOLIC_DIM + col;
            int32_t  raw = (int32_t)REG32(fc1_out_base_uc + idx * 4u);
            uint8_t  q   = (uint8_t)((raw >> shift) & 0xFFu);
            // row 0 packed as 4 bytes per word: word col/4, byte col%4
            uint32_t word_idx = col >> 2u;    // col / 4
            uint32_t byte_idx = col & 3u;     // col % 4
            uint32_t cur = REG32(blk_base + word_idx * 4u);
            cur &= ~(0xFFu << (byte_idx * 8u));
            cur |=  ((uint32_t)q << (byte_idx * 8u));
            REG32(blk_base + word_idx * 4u) = cur;
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // STEP 3 — FC2 tiled GEMV (same structure as main_inference.c)
    // ════════════════════════════════════════════════════════════════════════
    int32_t logits[FC2_M_PADDED];
    for (uint32_t i = 0; i < FC2_M_PADDED; i++) logits[i] = 0;

    for (uint32_t k = 0; k < FC2_NUM_K_TILES; k++) {
        uint32_t wgt_addr = DRAM_BASE_CACHED
                          + (FC2_WEIGHT_OFFSET + k * BLOCK_WORDS) * 4u;
        uint32_t act_addr = DRAM_BASE_CACHED
                          + (FC2_ACT_OFFSET + k * BLOCK_WORDS) * 4u;
        uint32_t out_tile_off  = FC2_OUTPUT_OFFSET + k * SP_RESULT_WORDS;
        uint32_t out_tile_addr = DRAM_BASE_CACHED + out_tile_off * 4u;

        accel_load(TILE_ID, wgt_addr, BLOCK_WORDS, SP_WGT_BASE);
        accel_wait_idle(TILE_ID);
        accel_load(TILE_ID, act_addr, BLOCK_WORDS, SP_ACT_BASE);
        accel_wait_idle(TILE_ID);
        accel_compute_at(TILE_ID, SP_ACT_BASE, SP_WGT_BASE, SP_OUT_BASE);
        accel_wait_idle(TILE_ID);
        accel_store(TILE_ID, out_tile_addr, SP_RESULT_WORDS, SP_OUT_BASE);
        accel_wait_idle(TILE_ID);
    }

    uint32_t t_end = timer_read();

    // CPU reduce FC2 partials
    for (uint32_t k = 0; k < FC2_NUM_K_TILES; k++) {
        uint32_t out_uc = DRAM_BASE_UC
                        + (FC2_OUTPUT_OFFSET + k * SP_RESULT_WORDS) * 4u;
        for (uint32_t row = 0; row < SYSTOLIC_DIM; row++) {
            for (uint32_t cls = 0; cls < FC2_M_ORIG; cls++) {
                logits[cls] += (int32_t)REG32(out_uc + (row * SYSTOLIC_DIM + cls) * 4u);
            }
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // STEP 4 — Argmax + UART report
    // ════════════════════════════════════════════════════════════════════════
    int32_t  best_val = logits[0];
    uint32_t best_idx = 0u;
    for (uint32_t i = 1; i < FC2_M_ORIG; i++) {
        if (logits[i] > best_val) { best_val = logits[i]; best_idx = i; }
    }

    uart_puts("LogitsHex:");
    for (uint32_t i = 0; i < FC2_M_ORIG; i++) {
        uart_putc(' ');
        uart_put_hex((uint32_t)logits[i]);
    }
    uart_puts("\r\n");

    uart_puts("Predicted: ");
    uart_put_dec((int32_t)best_idx);
    uart_puts("\r\n");

    if (TRUE_LABEL == 0xFFFFFFFFu) {
        uart_puts("True label: n/a\r\n");
    } else {
        uart_puts("True label: ");
        uart_put_dec((int32_t)TRUE_LABEL);
        uart_puts("\r\n");
    }

    if (best_idx == GOLDEN_PREDICTION) {
        uart_puts("PASS: matches golden\r\n");
    } else {
        uart_puts("FAIL: expected ");
        uart_put_dec((int32_t)GOLDEN_PREDICTION);
        uart_puts(" got ");
        uart_put_dec((int32_t)best_idx);
        uart_puts("\r\n");
    }

    uart_puts("Shift: ");
    uart_put_dec((int32_t)shift);
    uart_puts("\r\n");

    uint32_t cycles = t_end - t_start;
    uart_puts("Cycles: ");
    uart_put_hex(cycles);
    uart_puts("\r\n");

    REG32(GPIO_OUT) = (best_idx & 0x0Fu) | 0xF0u;
    uart_puts("Done.\r\n");

    while (1)
        ;
    return 0;
}
