TOPLEVEL_LANG = verilog
TOPLEVEL      = sram_ctrl
MODULE        = test_sram

SIM           = verilator
EXTRA_ARGS   += --trace --trace-structs -Wno-fatal
EXTRA_ARGS   += -I$(PWD)/../../rtl/top

VERILOG_SOURCES = \
    $(PWD)/../../rtl/top/soc_pkg.sv \
    $(PWD)/../../rtl/memory/sram_ctrl.sv

include $(shell cocotb-config --makefiles)/Makefile.sim
